portfolio = [
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/LO DE IRIS_cr.jpg", nombre:"LO DE IRIS" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/BESSONART DOS VENTANAS 1_cr.jpg", nombre:"BESSONART DOS VENTANAS 1" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/BESSONART DOS VENTANAS 3_cr.jpg", nombre:"BESSONART DOS VENTANAS 3" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonartinterior1.jpg", nombre:"Bessonart interior 1" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonartinterior2.jpg", nombre:"Bessonart interior 2" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonartinterior3.jpg", nombre:"Bessonart interior 3" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonart se fueron_cr.jpg", nombre:"Bessonart se fueron" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonart se quedaron_cr.jpg", nombre:"Bessonart se quedaron" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonart sillas 1_cr.jpg", nombre:"Bessonart sillas 1" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonart sillas 2_cr.jpg", nombre:"Bessonart sillas 2" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonart ventana patio 1_cr.jpg", nombre:"Bessonart ventana patio 1" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonart ventana patio 2_cr.jpg", nombre:"Bessonart ventana patio 2" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonart ventana patio_cr.jpg", nombre:"Bessonart ventana patio" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/bessonat interior.jpg", nombre:"Bessonat interior" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/bessonart/registradora de bessonart_cr.jpg", nombre:"Registradora de Bessonart" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/lo de ermilio/INTERIOR ERMILIO 2_cr.jpg", nombre:"Interior Emilio" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/lo de ermilio/lo de Alfredo Ermilio_cr.jpg", nombre:"Lo de Alfredo Ermilio" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/lo de ermilio/lo de ermilio 2_cr.jpg", nombre:"Lo de ermilio 2" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/lo de ermilio/lo de ermilio 3 detalle.jpg", nombre:"Lo de ermilio 3 detalle" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/lo de ermilio/lo de ermilio 3_cr.jpg", nombre:"Lo de ermilio 3" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/lo de ermilio/lo de ermilio 4_cr.jpg", nombre:"Lo de ermilio 4" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/lo de ermilio/lo de ermilio 5_cr.jpg", nombre:"Lo de ermilio 5" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/lo de ermilio/lo de Ermilio.jpg", nombre:"Lo de Ermilio" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/los principios/bar los principios 1_cr.jpg", nombre:"bar los principios 1" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/los principios/bar los principios 2_cr.jpg", nombre:"bar los principios 2" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/los principios/bar los principios 3_cr.jpg", nombre:"bar los principios 3" },
{ grupo:"Dibujos", pila:"Bares", archivo:"/lugares/bares/los principios/los principios.jpg", nombre:"los principios" },
{ grupo:"Dibujos", pila:"Lugares", archivo:"/lugares/Norte/en tilcara_cr.jpg", nombre:"en tilcara" },
{ grupo:"Dibujos", pila:"Lugares", archivo:"/lugares/Norte/purmamarca_cr.jpg", nombre:"purmamarca" },
{ grupo: "Dibujos", pila: "Lugares", archivo: "/lugares/Norte/tilcara_cr.jpg", nombre: "tilcara" },
{ grupo: "Dibujos", pila: "Modelos", archivo: "/modelo/florencia 2011/flor durmiendo.jpg", nombre: "flor durmiendo" },
{ grupo: "Dibujos", pila: "Modelos", archivo: "/modelo/florencia 2011/flor durmiendo 2_cr.jpg", nombre: "flor durmiendo 2" },
{ grupo: "Dibujos", pila: "Modelos", archivo: "/modelo/en casa/autorretrato con carandache_cr 2009.jpg", nombre: "autorretrato con carandache" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/en casa/autorretrato lapiz_cr 2009.jpg", nombre:"autorretrato lapiz" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/en casa/AUTORRETRATO_cr 2009.jpg", nombre:"Autorretrato" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/en casa/mama_cr 2011.jpg", nombre:"mama" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/en casa/martin retrato_cr 2011.jpg", nombre:"martin retrato" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/en casa/pie santi 2011.jpg", nombre:"pie santi" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/en casa/santi durmiendo_cr 2011.jpg", nombre:"santi durmiendo" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/florencia 2011/flor con baston_cr.jpg", nombre:"flor con baston" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/florencia 2011/flor sentada en el piaso_cr.jpg", nombre:"flor sentada en el piaso" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/paisanos 2012/Della Valle 1_cr.jpg", nombre:"Della Valle 1" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/paisanos 2012/della Valle_cr.jpg", nombre:"Della Valle" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/paisanos 2012/paisanos desfilando_cr.jpg", nombre:"paisanos desfilando" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/paisanos 2012/pezcado_cr.jpg", nombre:"Pescado" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/paisanos 2012/pezca_cr.jpg", nombre:"Pezca" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/suray/suray 1_cr.jpg", nombre:"suray 1" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/suray/suray 2_cr.jpg", nombre:"suray 2" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/suray/suray 3_cr.jpg", nombre:"suray 3" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/suray/suray dos poses_cr.jpg", nombre:"suray dos poses" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/suray/suray durmiendo en escorzo_cr.jpg", nombre:"suray durmiendo en escorzo" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/suray/suray durmiendo_cr.jpg", nombre:"suray durmiendo" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/suray/suray en tension_cr.jpg", nombre:"suray en tension" },
{ grupo:"Dibujos", pila:"Modelos", archivo:"/modelo/suray/suray parada de espaldas_cr.jpg", nombre:"suray parada de espaldas" },
{ grupo: "Dibujos", pila: "Modelos", archivo: "/modelo/suray/suray parada de frente_cr.jpg", nombre: "suray parada de frente" },
{ grupo: "Dibujos", pila: "Modelos", archivo: "/modelo/en casa/detalle santi durmiendo 2011.jpg", nombre: "detalle santi durmiendo" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2004/estacion de trenes.jpg", nombre:"estacion de trenes" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2004/Museo.jpg", nombre:"Museo" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2004/solar de Vieytes.jpg", nombre:"solar de Vieytes" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2004/turismo 2004.jpg", nombre:"turismo 2004" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2005/casa de Guiraldes.jpg", nombre:"casa de Guiraldes" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2005/ermita.jpg", nombre:"ermita" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2005/esquina vieytes y guiraldes.jpg", nombre:"esquina vieytes y guiraldes" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2005/kiosco 2005.jpg", nombre:"kiosco 2005" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2005/locomotora2.jpg", nombre:"locomotora 2" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2005/palomar 2005.jpg", nombre:"palomar" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2005/portoncito.jpg", nombre:"portoncito" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2005/pozo museo.jpg", nombre:"pozo museo" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2005/tiro federal.jpg", nombre:"tiro federal" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/baul 2006.jpg", nombre:"baul" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/bote.jpg", nombre:"bote" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/carreta 2006.jpg", nombre:"carreta" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/comisaria 2006.jpg", nombre:"comisaria" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/el taller de carlitos 2006.jpg", nombre:"el taller de carlitos" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/esquina plaza gomez.jpg", nombre:"esquina plaza gomez" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/farol.jpg", nombre:"farol" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/iglesia 2006.jpg", nombre:"iglesia" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/Lirios 2006.jpg", nombre:"Lirios" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/lo de Merti.jpg", nombre:"lo de Merti" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/puente viejo 2006.jpg", nombre:"puente viejo" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/rotonda 2006.jpg", nombre:"rotonda" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/tejido.jpg", nombre:"tejido" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2006/tinajas.jpg", nombre:"tinajas" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2007/Balcon de Bessonart.jpg", nombre:"Balcon de Bessonart" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2007/bicicletas.jpg", nombre:"bicicletas" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2007/calle arellano 2007.jpg", nombre:"calle arellano" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2007/casa del cura ingles 2007.jpg", nombre:"casa del cura ingles" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2007/casa parroquial 2007.jpg", nombre:"casa parroquial" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2007/esquina plaza arellano.jpg", nombre:"esquina plaza arellano" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2007/gato 2007.jpg", nombre:"gato" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2007/pulpito.jpg", nombre:"pulpito" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2008/antigua casona 2008.jpg", nombre:"antigua casona" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2008/estacion vagues 2008.jpg", nombre:"estacion vagues" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2008/farol ferrocarril 2008.jpg", nombre:"farol ferrocarril" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2008/iglesia2008.jpg", nombre:"iglesia2008" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2008/la lechuza 2008.jpg", nombre:"la lechuza" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2008/la vieja soderia.jpg", nombre:"la vieja soderia" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2008/locomotora 2008.jpg", nombre:"locomotora" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2008/posada de la plaza.jpg", nombre:"posada de la plaza" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2008/pozo La Blanqueada 2008.jpg", nombre:"pozo La Blanqueada" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2008/Se llama Ramon.jpg", nombre:"Se llama Ramon" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2009/antigua casona 2009.jpg", nombre:"antigua casona" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2009/capilla san jose 2009.jpg", nombre:"capilla san jose" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2009/casa vias 2009.jpg", nombre:"casa vias" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2009/donseg.jpg", nombre:"Don Segundo" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2009/la cerveceria 2009.jpg", nombre:"la cervecería" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2009/La Margarita 2009.jpg", nombre:"La Margarita" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2009/lo de arnaldi 2009.jpg", nombre:"lo de arnaldi" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2009/museo molina campos 2009.jpg", nombre:"museo molina campos" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2009/taller cristina.jpg", nombre:"taller cristina" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2009/tranquera.jpg", nombre:"tranquera" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/auto viejo.jpg", nombre:"auto viejo" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/bessonart 2010.jpg", nombre:"bessonart" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/bessonat interior.jpg", nombre:"bessonat interior" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/cafe de las artes 2010.jpg", nombre:"cafe de las artes" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/casa Aguilar.jpg", nombre:"casa Aguilar" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/casaburgueno.jpg", nombre:"Casa Burgueño" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/el tokio.jpg", nombre:"el tokio" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/la verduleria.jpg", nombre:"la verduleria" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/lode mateo 2010.jpg", nombre:"lode mateo" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/rancho.jpg", nombre:"rancho" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2010/tulipanes 2010.jpg", nombre:"tulipanes" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/bessonart 2011.jpg", nombre:"bessonart" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/campo 2011.jpg", nombre:"campo" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/country 2011.jpg", nombre:"country" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/el mitre 2011.jpg", nombre:"el mitre" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/el rosario de areco 2011.jpg", nombre:"el rosario de areco" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/guillermo 2011.jpg", nombre:"guillermo" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/lo de Ermilio 2011.jpg", nombre:"lo de Ermilio" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/los principios.jpg", nombre:"los principios" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/puerta patio 2011.jpg", nombre:"puerta patio" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/puesto en duggan 2011.jpg", nombre:"puesto en duggan" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/valijas 2011.jpg", nombre:"valijas" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2011/ventana 2011.jpg", nombre:"ventana" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/bar los principios 2012.jpg", nombre:"bar los principios" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/bessonart1.jpg", nombre:"bessonart" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/cachito althaparro.jpg", nombre:"cachito althaparro" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/campo la aguada.jpg", nombre:"campo la aguada" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/casco 2012.jpg", nombre:"casco" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/COLONIAL.jpg", nombre:"Colonial" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/della Valle.jpg", nombre:"della Valle" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/la estacion 2012.jpg", nombre:"la estacion" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/los malvones.jpg", nombre:"los malvones" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/LOS PRINCIPIOS 2012.jpg", nombre:"LOS PRINCIPIOS" },
{ grupo:"Dibujos", pila:"Areco", archivo:"/tapas revista don segundo/2012/rancho 2012.jpg", nombre:"rancho" },
{ grupo:"Grabados", pila:"Cuadros", archivo:"/el vivero de Male.jpg", nombre:"el vivero de Male" },
{ grupo:"Grabados", pila:"Cuadros", archivo:"/INeS.jpg", nombre:"Ines" },
{ grupo: "Grabados", pila: "Cuadros", archivo: "/MADUREZ EN LOS TULIPANES.jpg", nombre: "MADUREZ EN LOS TULIPANES" },
{ grupo: "Grabados", pila: "Cuadros", archivo: "/la radio de Horacio.jpg", nombre: "la radio de Horacio" },
{ grupo: "Grabados", pila: "Cuadros", archivo: "/tulipanes.jpg", nombre: "tulipanes" },
{ grupo: "Grabados", pila: "Cuadros", archivo: "/el fondo rojo.jpg", nombre: "el fondo rojo" },
{ grupo:"Grabados", pila:"Tulipanes", archivo:"/tulipanes 2008.jpg", nombre:"tulipanes" },
{ grupo:"Grabados", pila:"Tulipanes", archivo:"/tulipanes1.jpg", nombre:"tulipanes1" },
{ grupo:"Grabados", pila:"Tulipanes", archivo:"/tulipanes2.jpg", nombre:"tulipanes2" },
{ grupo:"Pintura", pila:"Naturaleza", archivo:"/naturaleza/acelgas y cebollas.jpg", nombre:"acelgas y cebollas" },
{ grupo:"Pintura", pila:"Naturaleza", archivo:"/naturaleza/DSC_0002_cr.jpg", nombre:"" },
{ grupo:"Pintura", pila:"Naturaleza", archivo:"/naturaleza/frente al club.jpg", nombre:"frente al club" },
{ grupo:"Pintura", pila:"Naturaleza", archivo:"/naturaleza/hemerocallis.jpg", nombre:"hemerocallis" },
{ grupo: "Pintura", pila: "Naturaleza", archivo: "/naturaleza/lirios plaza.jpg", nombre: "lirios plaza" },
{ grupo: "Pintura", pila: "Naturaleza", archivo: "/naturaleza/club de pescadores.jpg", nombre: "club de pescadores" },
{ grupo:"Pintura", pila:"Cosas", archivo:"/cosas/CAMIONETA_cr.jpg", nombre:"Camioneta" },
{ grupo:"Pintura", pila:"Cosas", archivo:"/cosas/huanuqueando.jpg", nombre:"huanuqueando" },
{ grupo:"Pintura", pila:"Cosas", archivo:"/cosas/libros de marcela_cr.jpg", nombre:"libros de marcela" },
{ grupo:"Pintura", pila:"Cosas", archivo:"/cosas/limon en silla_cr.jpg", nombre:"limon en silla" },
{ grupo:"Pintura", pila:"Cosas", archivo:"/cosas/picasso_cr.jpg", nombre:"picasso" },
{ grupo:"Pintura", pila:"Lugares", archivo:"/lugares/BESSONART_cr_cr.jpg", nombre:"BESSONART" },
{ grupo:"Pintura", pila:"Lugares", archivo:"/lugares/Ermilio interior_cr.jpg", nombre:"Ermilio interior" },
{ grupo:"Pintura", pila:"Lugares", archivo:"/lugares/interior de lo de Ermilio_cr.jpg", nombre:"interior de lo de Ermilio" },
{ grupo:"Pintura", pila:"Lugares", archivo:"/lugares/interior de los principios 1_cr.jpg", nombre:"interior de los principios 1" },
{ grupo:"Pintura", pila:"Lugares", archivo:"/lugares/interior de los principios 2_cr.jpg", nombre:"interior de los principios 2" },
{ grupo:"Pintura", pila:"Lugares", archivo:"/lugares/la comisaria_cr.jpg", nombre:"la comisaria" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/gatito siames_cr 2003.jpg", nombre:"gatito siames" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/guillermina adormecida_cr.jpg", nombre:"guillermina adormecida" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/guillermina sentada_cr.jpg", nombre:"guillermina sentada" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/manuela en sillon_cr 2003.jpg", nombre:"manuela en sillon" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/manuela recostada con uniforme_cr 2003.jpg", nombre:"manuela recostada con uniforme" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/martin sentado_cr 2011.jpg", nombre:"martin sentado" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/secretaria_cr 2003.jpg", nombre:"secretaria" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/Sivori_cr.jpg", nombre:"Sivori" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray apoyada_cr 2011.jpg", nombre:"suray apoyada" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray de cabeza_cr 2012.jpg", nombre:"suray de cabeza" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray de espaldas_cr 2012.jpg", nombre:"suray de espaldas" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray en el piso_cr 2012.jpg", nombre:"suray en el piso" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray en manto floreado_cr 2012.jpg", nombre:"suray en manto floreado" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray recostada_cr 2012.jpg", nombre:"suray recostada" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray sentada de espaldas_cr 2012.jpg", nombre:"suray sentada de espaldas" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray sentada_cr 2012.jpg", nombre:"suray sentada" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray tirada detalle 2012.jpg", nombre:"suray tirada detalle" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray tirada_cr 2012.jpg", nombre:"suray tirada" },
{ grupo:"Pintura", pila:"Modelo", archivo:"/modelo/suray tomandose la rodilla detalle 2012.jpg", nombre:"suray tomandose la rodilla detalle" },
{ grupo: "Pintura", pila: "Modelo", archivo: "/modelo/suray tomandose la rodilla_cr 2012.jpg", nombre: "suray tomandose la rodilla" },
{ grupo: "Pintura", pila: "Modelo", archivo: "/modelo/Manet_cr 2011.jpg", nombre: "Manet" },
{ grupo: "Varios", pila: "", archivo: "/Cuentos/elbichopelota.jpg", nombre: "El bicho Pelota" },
{ grupo: "Varios", pila: "", archivo: "/Cuentos/laardillitagordita.jpg", nombre: "La Ardillita Gordita" },
{ grupo: "Varios", pila: "", archivo: "/ESCULTURA/DSC_0100.jpg", nombre: "Sin Nombre" }
];

